# .travis.yml
language: java

jdk:
  - oraclejdk8

install:
  - curl -s toast.sh/install | bash

before_script:
  - ~/toaster/toast.sh version next $TRAVIS_BRANCH $TOAST_TOKEN nalbam

script:
  - mvn clean package

after_success:
  - mvn cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
  - ~/toaster/toast.sh version save none $TOAST_TOKEN nalbam

notifications:
  slack: nalbam:lZm5eyurcsoKxZgHSnNZGQYY
