# .travis.yml
language: java

jdk:
  - oraclejdk8

install:
  - mvn -s settings.xml -version

script:
  - mvn -s settings.xml clean compile

after_success:
  - mvn -s settings.xml cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report

notifications:
  slack: nalbam:lZm5eyurcsoKxZgHSnNZGQYY
