server:
  port: ${PORT:8080}

spring:
  jackson:
    time-zone: Asia/Seoul
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

encrypt:
  key: ${ENCRYPT_KEY:RandomString}

management:
  context-path: /admin
