server:
  port: ${PORT:8888}

spring:
  jackson:
    time-zone: Asia/Seoul
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

encrypt:
  key: ${ENCRYPT_KEY:RandomString}

management:
  security:
    enabled: false

---

spring:
  profiles: default
#eureka:
#  instance:
#    hostName: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: dev
eureka:
  instance:
    preferIpAddress: true
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: http://dev-eureka-server/eureka/

---

spring:
  profiles: prod
eureka:
  instance:
    preferIpAddress: true
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: http://prod-eureka-server/eureka/

---

spring:
  profiles: test
eureka:
  client:
    enabled: false
