server:
  port: ${PORT:8888}

spring:
  jackson:
    time-zone: Asia/Seoul
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

encrypt:
  key: ${ENCRYPT_KEY:RandomString}

management:
  security:
    enabled: false

---

spring:
  profiles: default

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/

---

spring:
  profiles: dev

eureka:
  instance:
    preferIpAddress: true
    nonSecurePort: ${EUREKA_SERVER_PORT:8761}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:eureka-server}:${EUREKA_SERVER_PORT:8761}/eureka/

---

spring:
  profiles: prod

eureka:
  instance:
    preferIpAddress: true
    nonSecurePort: ${EUREKA_SERVER_PORT:8761}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:eureka-server}:${EUREKA_SERVER_PORT:8761}/eureka/

---

spring:
  profiles: test

eureka:
  client:
    enabled: false
