server:
  port: ${PORT:8888}

management:
  context-path: /admin

logging:
  path: /data/logs
  level:
    root: warn

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nalbam/nalbam-config-repo
          username: ${USERNAME:username}
          password: ${PASSWORD:password}
