kind: BuildConfig
apiVersion: v1
metadata:
  name: config-server-pipeline
spec:
  type: JenkinsPipeline
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
          stage 'build'
          openshiftBuild(buildConfig: 'config-server', showBuildLogs: 'true')
          stage 'deploy'
          openshiftDeploy(deploymentConfig: 'config-server')
        }
